BITSnews 2.0/bitsnewslite/bitsnewslite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('news.urls')),
    url(r'^admin/', admin.site.urls),
]

BITSnews 2.0/bitsnewslite/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^posts/(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
	url(r'^aboutus/$', views.aboutus, name='aboutus'),
	url(r'^posts/$', views.posts, name='posts'),
	url(r'^event/$', views.event, name='event'),
	url(r'^gallery/$', views.gallery, name='gallery'),
	url(r'^contributors/$', views.contri, name='contri')
]

BITSnews 2.0/bitsnewslite/news/models.py
from django.db import models
import datetime

# Create your models here.

class Ticker(models.Model):
	ticker_text = models.CharField(max_length=100)
	def __str__(self):
		return self.ticker_text

class Article(models.Model):
	article_title = models.CharField(max_length=100)
	article_text = models.TextField()
	article_author = models.CharField(max_length=40)
	article_image = models.CharField(max_length=100)
	article_date = models.DateTimeField('date published')
	article_summary = models.TextField(default="I wil put in shit, wait! ")
	def __str__(self):
		return self.article_title

class Category(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	TECHNOLOGY = 'TECH'		
	OASIS = 'OASIS'
	DEPARTMENTS = 'DEP'
	CLUBS = 'CLUB'
	ACADEMICS = 'ACADS'
	CATEGORY_CHOICES = (
			(TECHNOLOGY, 'Technology'),
			(OASIS, 'Oasis'),
			(DEPARTMENTS, 'Departments'),
			(CLUBS, 'Clubs'),
			(ACADEMICS, 'Academics'),
		)
	category = models.CharField(
			max_length = 10,
			choices = CATEGORY_CHOICES,
		)
	def __str__(self):
		return self.category

class Picture(models.Model):
	pics_image = models.CharField(max_length=100)
	def __str__(self):
		return self.pics_image

class Video(models.Model):
	video_video = models.CharField(max_length=200)
	def __str__(self):
		return self.video_video


class Event(models.Model):
	event_title = models.CharField(max_length=100)
	event_summary = models.TextField(default=" I will put in shit, wait")
	event_location = models.CharField(max_length=30)
	event_date = models.DateTimeField('date of event')
	event_image = models.CharField(max_length=100, null=True, blank=True)
	def __str__(self):
		return self.event_image

class PollQuestion(models.Model):
	poll_question = models.CharField(max_length=200)
	poll_date = models.DateTimeField('date published')

class PollChoice(models.Model):
	question = models.ForeignKey(PollQuestion, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

#class DateHead(models.Model):
#	date_now = datetime.datetime.now()

BITSnews 2.0/bitsnewslite/news/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse

from .models import Article, Picture, Video, Event, PollQuestion, PollChoice, Category, Ticker

# Create your views here.
def index(request):
	article_list = Article.objects.order_by('-article_date')
	picture_list = Picture.objects.all()
	video_list = Video.objects.all()
	pollq_list = PollQuestion.objects.all()
	pollc_list = PollChoice.objects.all()
	ticker_list = Ticker.objects.all()
	#date_list = DateHead.date_now
	template = loader.get_template('news/Home.html')
	context = {
	'article_list': article_list,
	'picture_list': picture_list,
	'video_list': video_list,
	'pollq_list': pollq_list,
	'pollc_list': pollc_list,
	'ticker_list': ticker_list,
	}
	return HttpResponse(template.render(context, request))


def detail(request, article_id):
	article = Article.objects.get(pk=article_id)
	
	#date_list = DateHead.date_now
	return render(request, 'news/post.html', {'article': article})

def posts(request):
	article_list = Article.objects.order_by('-article_date')
	return render(request, 'news/posts.html', {'article_list': article_list})

def event(request):
	events_list = Event.objects.order_by('-event_date')
	return render(request, 'news/events.html', {'events_list': events_list})

def gallery(request):
	picture_list = Picture.objects.all()
	return render(request, 'news/gall.html', {'picture_list': picture_list})

def aboutus(request):
	#date_list = DateHead.date_now
	return render(request, 'news/About.html', {})	

def contri(request):
	#date_list = DateHead.date_now
	return render(request, 'news/Contributors.html', {})		

BITSnews 2.0/bitsnewslite/news/templates/news/About.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400|Roboto:400,500" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'news/Theme.css' %}">
  <link rel="stylesheet" href="{% static 'news/About.css' %}">
</head>
<body>
  <nav class="navbar navbar-inverse" id="date_navbar">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <p class="date_p">October 12, 2016</p>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect fb_effect"><i class="fa fa-facebook" aria-hidden="true"></i></span></a></li>
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect tw_effect"><i class="fa fa-twitter" aria-hidden="true"></i></span></a></li>
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect you_effect"><i class="fa fa-youtube-play" aria-hidden="true"></i></span></a></li>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>
  <nav class="navbar navbar-default" id="#navbar_logo" style="margin-bottom: 0px; background-color: white; border: none;">
    <div class="container text-center">
      <a class="navbar-brand" href="..">
        <img alt="BitsNewsLite" src="{% static 'news/images/logo.jpg' %}" style="margin: auto">
      </a>
    </div>
      <!-- Brand and toggle get grouped for better mobile display -->
  </nav>
  <nav class="navbar navbar-default" id="navbar_main">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav" id="left_nav">
          <li><a class="link active" href=".."><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
          <li><a class="link" href="../posts/">Posts</a></li>
          <li><a class="link" href="../event">Events</a></li>
          <li><a class="link" href="map.html">Campus Map</a></li>
          <li><a class="link" href="../gallery/">Gallery</a></li>
          <li><a class="link" href="essential.html">Essentials</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-left text-right">
            <div class="form-group">
              <input type="text" class="search_bar form-control" placeholder="Search">
            </div>
            <button type="submit" class="search_btn btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </form>
          <li><a class="link" href="../contributors/">Contributors</a></li>
          <li><a class="link" href="../aboutus/">About Us</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <!--- navend -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-xs-12 nopadding">
        <div class="break">

        </div>
        <div class="box_theme">
          <p class="title offset_title_box">
            ABOUT US
          </p>
          <div class="break4">

          </div>
          <p class="text_about">
            We’ve all envisioned it since the inception, but it wasn’t there. Something was needed, something that has it all. Be it for who are here or for who aren’t! A ‘tell-it-all’ portal! Multiple attempts have been made in the past to get it on, but all in vain. Something was done wrong. Idea is one, implementations are many! Focus is one, minds are many!
            <br><br>
            A Surreal Endeavour to glorify BITS Pilani!
            <br><br>
            From the time we decided on coming to BITS Pilani and googling everything about it, trying to find a compiled a portsl got all our needs but it just wasn't there and to the time when we've graduated and want to know about what-how-why of our Alma Mater, for all that, we bring you BITSNewsLite!
            <br><br>
            For all on-campus activities! For all BITSian ventures and endeavours! A news hub of all BITSian activities! And a beacon of BITSian awesomeness for the world!
            <br><br>
            In concordance with clubs and departments of BITS Pilani, we’re presenting you BITS NewsLite which is a platform for BITSian community to showcase their creative, literary and technical talent. We will be putting up articles of all genre, interviews, polls, event updates and general news.
          </p>
          <div class="break">

          </div>
        </div>
        <div class="break">

        </div>
      </div>
    </div>
  <div class="break">
  </div>
</body>
</html>

BITSnews 2.0/bitsnewslite/news/templates/news/post.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400|Roboto:400,500" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'news/Theme.css' %}">
  <link rel="stylesheet" href="{% static 'news/post.css' %}">
</head>
<body>
  <nav class="navbar navbar-inverse" id="date_navbar">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <p class="date_p">October 12, 2016</p>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect fb_effect"><i class="fa fa-facebook" aria-hidden="true"></i></span></a></li>
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect tw_effect"><i class="fa fa-twitter" aria-hidden="true"></i></span></a></li>
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect you_effect"><i class="fa fa-youtube-play" aria-hidden="true"></i></span></a></li>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>
  <nav class="navbar navbar-default" id="#navbar_logo" style="margin-bottom: 0px; background-color: white; border: none;">
    <div class="container text-center">
      <a class="navbar-brand" href="../..">
        <img alt="BitsNewsLite" src="{% static 'news/images/logo.jpg' %}" style="margin: auto">
      </a>
    </div>
      <!-- Brand and toggle get grouped for better mobile display -->
  </nav>
  <nav class="navbar navbar-default" id="navbar_main">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav" id="left_nav">
          <li><a class="link" href="../.."><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
          <li><a class="link" href="..">Posts</a></li>
          <li><a class="link" href="../../event/">Events</a></li>
          <li><a class="link" href="map.html">Campus Map</a></li>
          <li><a class="link" href="../../gallery/">Gallery</a></li>
          <li><a class="link" href="essential.html">Essentials</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-left text-right">
            <div class="form-group">
              <input type="text" class="search_bar form-control" placeholder="Search">
            </div>
            <button type="submit" class="search_btn btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </form>
          <li><a class="link" href="../../contributors/">Contributors</a></li>
          <li><a class="link" href="../../aboutus/">About Us</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <!--- navend -->
  <div class="container">
    <!-- <div class="row ticker">
    <div class="ticker_title">
    <p>
    Latest news
  </p>
</div>
<div class="col-lg-10 col-xs-10 ticker_text_container">
<p class="ticker_text">
edqw fqwfqwfqw fqwfqw fqwfqw diuqw hfui qwgfu ibouchqwui ghuh
</p>
</div>
</div> -->
<div class="row">
  <div class="col-lg-8 col-xs-12">
    <div class="box_theme">

    <div class="categories_top">
      {% for category in article.category_set.all %}
      <p class="categories">{{ category.category }}</p>
      {% endfor %}
    </div>
      <h2 class="post-title2">{{ article.article_title }}</h2>
        <div class="entry-meta detail_1">
              <span class="hover1 date1">
                 <span class="glyphicon glyphicon-calendar"></span>
                 <a class="url fn n" href="">{{ article.article_date|date:"d M Y" }}</a>
               </span>
               <span>
               </span>
               <span class="hover1 user1">
                   <span class="glyphicon glyphicon-user"></span>
                   <a class="url fn n" href="">{{ article.article_author }}</a>
               </span>
        </div>
        <div class="nopadding">
          <div class="col-lg-12 col-xs-12 article2 nopadding nomargin">
            <div class="col-lg-12 col-xs-12 nopadding article_img_container2">
              <a href="#"><img class="article_img2" src="{{ article.article_image }}" alt="img" /></a>
            </div>
            <div class="col-lg-11 col-xs-11 article_text2 nopadding">
              <p class="post_content">
                {{ article.article_text }}
                  </p></a>
                </div>
                <div class="break4"></div>
              </div>

            </div>
            </div>
          </div>
            <div class="col-lg-4 col-xs-12 nopadding">
              <div class="sidebar">
                <div class="box_theme">
                  <p class="offset_title_box title">
                    ARCHIVES
                  </p>
                  <div class="break4"></div>
                  <ul>
                    <li>
                      <a href="#" class="archives">October 2016</a>
                    </li>
                  </ul>
                </div>
                <div class="break0"></div>
                <div class="box_theme">
                  <p class="offset_title_box title">
                      CATEGORIES
                  </p>
                  <div class="break4"></div>
                  <ul class="cat_list">
                    <li>
                      <a href="#" class="categories">Cat 1</a>
                    </li>
                  </ul>
                </div>
                <div class="break0"></div>
              </div>
            </div>
          </div>
          <div class="break"></div>
        </div>
        <div class="break4"></div>
      </body>
      </html>

BITSnews 2.0/bitsnewslite/news/templates/news/posts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400|Roboto:400,500" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'news/Theme.css' %}">
  <link rel="stylesheet" href="{% static 'news/post.css' %}">
</head>
<body>
  <nav class="navbar navbar-inverse" id="date_navbar">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <p class="date_p">October 12, 2016</p>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect fb_effect"><i class="fa fa-facebook" aria-hidden="true"></i></span></a></li>
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect tw_effect"><i class="fa fa-twitter" aria-hidden="true"></i></span></a></li>
        <li><a href="http://www.facebook.com" target="_blank" class="nopadding"><span class="icont_effect you_effect"><i class="fa fa-youtube-play" aria-hidden="true"></i></span></a></li>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>
  <nav class="navbar navbar-default" id="#navbar_logo" style="margin-bottom: 0px; background-color: white; border: none;">
    <div class="container text-center">
      <a class="navbar-brand" href="..">
        <img alt="BitsNewsLite" src="{% static 'news/images/logo.jpg' %}" style="margin: auto">
      </a>
    </div>
      <!-- Brand and toggle get grouped for better mobile display -->
  </nav>
  <nav class="navbar navbar-default" id="navbar_main">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav" id="left_nav">
          <li><a class="link active" href=".."><span class="glyphicon glyphicon-home" aria-hidden="true"></span></a></li>
          <li><a class="link" href="#">Posts</a></li>
          <li><a class="link" href="../event/">Events</a></li>
          <li><a class="link" href="map.html">Campus Map</a></li>
          <li><a class="link" href="../gallery/">Gallery</a></li>
          <li><a class="link" href="essential.html">Essentials</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <form class="navbar-form navbar-left text-right">
            <div class="form-group">
              <input type="text" class="search_bar form-control" placeholder="Search">
            </div>
            <button type="submit" class="search_btn btn btn-default"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </form>
          <li><a class="link" href="../contributors/">Contributors</a></li>
          <li><a class="link" href="../aboutus/">About Us</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <!--- navend -->
  <div class="container">
    <!-- <div class="row ticker">
      <div class="ticker_text_container text-right">
        <p class="ticker_text">
        edqw fqwfqwfqw fqwfqw fqwfqw diuqw hfui qwgfu ibouchqwui ghuh
        </p>
      </div>
    </div> -->
    <div class="row nopadding">
      <div class="col-lg-8 col-xs-12 nopadding">
        <div class="box_theme">
          <p class="offset_title_box title">
            RECENT POSTS
          </p>
          <div class="break4"></div>
          {% for article in article_list %}
          <div class="col-lg-12 col-xs-12 article">
            <div class="col-lg-12 col-xs-12 nopadding article_img_container pointer_hover">
              <a href="#"><img class="article_img" src="{{ article.article_image }}" alt="img" /></a>
            </div>
            <div class="col-lg-11 col-xs-11 article_text nopadding pointer_hover">
              <div class="categories_small">
                {% for cat in article.category_set.all %}
                <p class="categories"> {{ cat.category }}</p>
                {% endfor %}
              </div>
              <a href="{{ article.id }}/"><h3 class="post-title">{{ article.article_title }}</h3></a>
                <div class="entry-meta">
					            <span class="hover1">
                         <span class="glyphicon glyphicon-calendar"></span>
                         <a class="url fn n" href="">{{ article.article_date|date:"d M Y" }}</a>
                       </span>
                       <span class="hover1">
                           <span class="glyphicon glyphicon-user"></span>
                           <a class="url fn n" href="">{{ article.article_author }}</a>
                       </span>
    	            </div>
                      <p class="post_content">{{ article.article_summary }}</p>
                      </div>
                      <div class="break4"></div>
                    </div>
      <div class="break4"></div>
      {% endfor %}
      </div>

    </div>
      
      <div class="col-lg-4 col-xs-12 nopadding">
        <div class="sidebar">
          <div class="box_theme">
            <p class="offset_title_box title">
              ARCHIVES
            </p>
            <div class="break4"></div>
            <ul>
              <li>
                <a href="#" class="archives">October 2016</a>
              </li>
            </ul>
          </div>
          <div class="break0"></div>
          <div class="box_theme">
            <p class="offset_title_box title">
                CATEGORIES
            </p>
            <div class="break4"></div>
            <ul class="cat_list">
              <li>
                <a href="#" class="categories">TECH</a>
                <a href="#" class="categories">OASIS</a>
                <a href="#" class="categories">DEP</a>
                <a href="#" class="categories">CLUB</a>
                <a href="#" class="categories">ACADS</a>
              </li>
            </ul>
          </div>
          <div class="break0"></div>
        </div>
      </div>
    </div>
    <div class="break"></div>
  </div>
  <div class="break4"></div>
</body>
</html>